
<HTML>
<BODY>
<?php 
$v1 = "";
echo $v1;
?>
<UL></UL>
</BODY>
<SCRIPT TYPE="TEXT/JAVASCRIPT" SRC="JAVASCRIPT/JQUERY.JS"></SCRIPT>
<SCRIPT TYPE="TEXT/JAVASCRIPT" SRC="JAVASCRIPT/TESTSCRIPT.JS"></SCRIPT>
</HTML>